name: strava_app
channels:
  - defaults
  - conda-forge
  - intel
dependencies:
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask
  - requests
  - numpy
  - pandas
  - pip

